LPS-83920 Update logic to check for .lfrbuild-releng-skip-update-file-versions in parent directories
brianchandotcom/liferay-portal pull request #61688
Opened 2018-07-27 23:30 UTC by petershin

@Ithildir

2018-07-27 23:30 UTC, liferay-continuous-integration commented
CI is automatically triggering &quot;ci:test:sf&quot; and &quot;ci:test:relevant&quot; for this pull to run Source Formatter and relevant tests.

Comment &quot;ci:test&quot; to run the full PR Tester for this pull.

2018-07-27 23:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/270/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-source-format/builds/270/jenkins-report.html">here</a>.</b></p>

2018-07-27 23:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/3704/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3704/jenkins-report.html">here</a>.</b></p>

2018-07-27 23:32 UTC, petershin commented
ci:reopen

2018-07-27 23:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 1 minute 29 seconds 53 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f4f3763e7929b9bc71f5f717bead7b5077f4a1a0">f4f3763e7929b9bc71f5f717bead7b5077f4a1a0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/petershin/liferay-portal/tree/lfm-072710">lfm-072710</a><br/>Branch GIT ID: <a href="https://github.com/petershin/liferay-portal/commit/eeb5ed552dc1e921873372a5fae4de742da50554">eeb5ed552dc1e921873372a5fae4de742da50554</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/270/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/270/jenkins-report.html">here</a>.</h5></details></html>

2018-07-28 00:04 UTC, Ithildir requested changes

2018-07-28 00:04 UTC, Ithildir commented on modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/LiferayOSGiDefaultsPlugin.java
> +					File markerFile = GradleUtil.getRootDir(
The `getRootDir` method returns a directory, so the variable should be called `dir`, `markerDir`, or something like that.

2018-07-28 00:14 UTC, liferay-continuous-integration commented
Closing and locking pull request because pull requests sent to this user may not be updated. Please resend this pull request.

2018-07-28 00:14 UTC, closed without merging